// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmalywoeeqtuackhebab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttYWx5d29lZXF0dWFja2hlYmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNjQyMDgsImV4cCI6MjA4NDg0MDIwOH0.s941AlczQtXIt_4fpb8uTjxZMz3WZnw5rFzQ-UgjMKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});